### ISSUE TITLE
Information about assignment 3

### ISSUE THREAD

**Issue by hugonugraM** [FacultadInformatica-LinkedData/Curso2019-2020-OpenDataKnowledgeGraphs#13]
Hello to all, I would like to know if inside our new folder we have to add the whole project or just the the files related to the tasks 6 and 7?

**Comment by paoespinozarias** [comment]
Hi Hugo,
In order to send your pull request with the Assignment 3 solution, you only need to add your task6 and task7 Java files inside the new folder.
